name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Dotnet tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version : '8.0.x'

      - name: Run Tests
        run: dotnet test src/DevOpsDaysTasks.Core.Tests

      - name: Run Integration Tests
        run: dotnet test src/DevOpsDaysTasks.IntegrationTests

      - name: Create release dir
        run: mkdir DevOpsDaysTasks

      - name: Build a Release
        run: dotnet publish -c Release src\DevOpsDaysTasks.UI\ -o DevOpsDaysTasks /p:Version=1.0.0 /p:VersionName=chaos

      - name: Populate template folder
        run: |
          mkdir DevOpsDaysTasks\Templates
          cp workshop_material\default-tasks.xml DevOpsDaysTasks\Templates\

      - name: Populate help folder
        run: |
          mkdir DevOpsDaysTasks\Help
          cp workshop_material\Help.pdf DevOpsDaysTasks\Help

